# Generated by Django 5.2.13 on 2026-05-03 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeline_entries',
                'indexes': [models.Index(fields=['user', '-created_at'], name='timeline_entries_user_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='timeline_entries_user_post_uniq')],
            },
        ),
    ]
