/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証中ユーザー情報 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分が所属するチャンネル一覧 (既読 / 最新メッセージ ID 同梱) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelList"];
                    };
                };
            };
        };
        put?: never;
        /** チャンネル作成 (作成者は自動で admin として join) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChannelCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 既読 cursor を進める (ADR 0002 - 単調増加ガード) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ChannelId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message_id: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** public チャンネルに参加 (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ChannelId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 既にメンバー / 新規参加どちらでも 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinResponse"];
                    };
                };
                /** @description public 以外のチャンネル */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ai-worker による直近メッセージの要約 (モック) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ChannelId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Summary"];
                    };
                };
                /** @description ai-worker 通信失敗 (graceful degradation 改修候補) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: components["parameters"]["ChannelIdInPath"];
            };
            cookie?: never;
        };
        /** チャンネルのメッセージ (cursor ページング、新しい順) */
        get: {
            parameters: {
                query?: {
                    /** @description この ID 未満を返す */
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    channel_id: components["parameters"]["ChannelIdInPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagesPage"];
                    };
                };
            };
        };
        put?: never;
        /** メッセージ投稿 (ActionCable で fan-out) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel_id: components["parameters"]["ChannelIdInPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MessageCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            id: number;
            display_name: string;
            /** Format: email */
            email: string;
        };
        Channel: {
            id: number;
            name: string;
            /** @enum {string} */
            kind: "public" | "private" | "dm";
            topic: string | null;
            last_read_message_id?: number | null;
            latest_message_id?: number | null;
        };
        ChannelList: {
            channels: components["schemas"]["Channel"][];
        };
        ChannelCreateRequest: {
            name: string;
            /**
             * @default public
             * @enum {string}
             */
            kind: "public" | "private" | "dm";
            topic?: string;
        };
        ReadResponse: {
            last_read_message_id: number | null;
            advanced: boolean;
        };
        JoinResponse: {
            id: number;
            channel: components["schemas"]["Channel"];
        };
        Message: {
            id: number;
            body: string;
            parent_message_id: number | null;
            /** Format: date-time */
            edited_at: string | null;
            /** Format: date-time */
            created_at: string;
            user: {
                id: number;
                display_name: string | null;
            };
        };
        MessagesPage: {
            messages: components["schemas"]["Message"][];
            next_cursor: number | null;
        };
        MessageCreateRequest: {
            body: string;
            parent_message_id?: number | null;
        };
        Summary: {
            channel_name: string;
            message_count: number;
            participants: string[];
            summary: string;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: {
        ChannelId: number;
        ChannelIdInPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
