# Generated by Django 5.2.13 on 2026-05-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_edges', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_edges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow_edges',
                'indexes': [models.Index(fields=['followee', 'follower'], name='follow_edges_reverse_idx'), models.Index(fields=['followee', 'created_at'], name='follow_edges_followee_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followee'), name='follow_edges_pk')],
            },
        ),
    ]
