/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開済み動画一覧 (新しい順) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoList"];
                    };
                };
            };
        };
        put?: never;
        /** 動画メタデータの直接作成 (Phase 2 互換 / 認証なし管理用) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VideoCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoDetail"];
                    };
                };
                /** @description user_email に該当する User が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開済み動画の全文検索 (MySQL FULLTEXT ngram) */
        get: {
            parameters: {
                query?: {
                    /** @description 検索クエリ。BOOLEAN モードのメタ文字は除去される */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 動画詳細 (viewable=ready/published のみ) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["VideoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoDetail"];
                    };
                };
                /** @description 非公開状態 (uploaded / transcoding / failed) を含む */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 動画状態のポーリング (どの状態でも 200 を返す) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["VideoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoStatus"];
                    };
                };
                /** @description ID 不在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 関連動画 (ai-worker でスコアリング、失敗時は degraded:true) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["VideoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 通常成功 / ai-worker 失敗時の degraded 応答も含む */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationsResponse"];
                    };
                };
                /** @description 対象動画が viewable でない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ready 状態を published へ遷移 (ADR 0001) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["VideoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 公開成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoDetail"];
                    };
                };
                /** @description ID 不在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 状態機械ガード違反 (非 ready から呼ばれた) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StateConflict"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: components["parameters"]["VideoIdInPath"];
            };
            cookie?: never;
        };
        /** コメント一覧 (1段スレッド構造) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    video_id: components["parameters"]["VideoIdInPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentList"];
                    };
                };
                /** @description 対象動画が viewable でない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** コメント / 返信を投稿 (parent_id 指定で返信) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    video_id: components["parameters"]["VideoIdInPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreateRequest"];
                };
            };
            responses: {
                /** @description 投稿成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
                /** @description video が viewable でない / user_email 不在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー (本文空 / 2段以上のスレッド等) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 動画ファイルをアップロードし transcoding 状態へ遷移 (ADR 0001) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: email */
                        user_email: string;
                        title: string;
                        description?: string;
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created (status: transcoding) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                /** @description user_email 不在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
            service?: string;
            /** Format: date-time */
            time?: string;
        };
        Author: {
            id: number;
            name: string;
        };
        /** @enum {string} */
        VideoStatusEnum: "uploaded" | "transcoding" | "ready" | "published" | "failed";
        VideoSummary: {
            id: number;
            title: string;
            status: components["schemas"]["VideoStatusEnum"];
            duration_seconds: number | null;
            /** Format: date-time */
            published_at: string | null;
            author: components["schemas"]["Author"];
            tags: string[];
            /** Format: uri */
            thumbnail_url: string | null;
        };
        VideoDetail: components["schemas"]["VideoSummary"] & {
            description: string | null;
        };
        VideoList: {
            items: components["schemas"]["VideoSummary"][];
        };
        SearchResult: {
            items: components["schemas"]["VideoSummary"][];
            query: string;
        };
        VideoStatus: {
            id: number;
            status: components["schemas"]["VideoStatusEnum"];
        };
        RecommendedVideo: components["schemas"]["VideoSummary"] & {
            score: number;
        };
        RecommendationsResponse: {
            items: components["schemas"]["RecommendedVideo"][];
            /** @description ai-worker と通信できなかった場合 true (graceful degradation) */
            degraded?: boolean;
        };
        Comment: {
            id: number;
            body: string;
            /** Format: date-time */
            created_at: string;
            author: components["schemas"]["Author"];
            parent_id: number | null;
            replies?: components["schemas"]["Comment"][];
        };
        CommentList: {
            items: components["schemas"]["Comment"][];
        };
        CommentCreateRequest: {
            /** Format: email */
            user_email: string;
            body: string;
            parent_id?: number | null;
        };
        VideoCreateRequest: {
            /** Format: email */
            user_email: string;
            title: string;
            description?: string;
            duration_seconds?: number;
            status?: components["schemas"]["VideoStatusEnum"];
            tags?: string[];
        };
        UploadResponse: {
            id: number;
            title: string;
            status: components["schemas"]["VideoStatusEnum"];
            author: components["schemas"]["Author"];
            original_filename: string;
        };
        Error: {
            error: string;
        };
        ValidationError: {
            errors: string[];
        };
        StateConflict: {
            /** @example invalid_transition */
            error: string;
            detail?: string;
        };
    };
    responses: never;
    parameters: {
        VideoId: number;
        VideoIdInPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
