"""ADR 0003: /summarize の deterministic mock。同じ transcript_seed なら同じ body / input_hash を返す。

policy: 外部 LLM API は呼ばない。固定の前置きと末尾 + 入力ハッシュを混ぜることで「決定論的だが入力で変わる」モックにする。
"""

import hashlib

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.security import verify_internal_token

router = APIRouter()


class SummarizeRequest(BaseModel):
    meeting_id: int
    recording_id: int
    transcript_seed: str = Field(min_length=1)


class SummarizeResponse(BaseModel):
    body: str
    input_hash: str


_MOCK_PREFIX = "[mock summary] "
_MOCK_BULLETS = [
    "decisions: confirmed roadmap and ownership for the next sprint.",
    "action items: capture follow-ups and notify absent participants.",
    "risks: highlight blockers raised during the discussion.",
]


def _deterministic_summary(seed: str) -> tuple[str, str]:
    digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()
    short = digest[:12]
    chosen_index = int(digest[:2], 16) % len(_MOCK_BULLETS)
    body = (
        f"{_MOCK_PREFIX}meeting fingerprint={short}\n"
        f"- {_MOCK_BULLETS[chosen_index]}\n"
        f"- generated by deterministic mock (no external LLM call)."
    )
    return body, digest


@router.post("/summarize", response_model=SummarizeResponse, dependencies=[Depends(verify_internal_token)])
async def summarize(payload: SummarizeRequest) -> SummarizeResponse:
    body, digest = _deterministic_summary(payload.transcript_seed)
    return SummarizeResponse(body=body, input_hash=digest)
